### ISSUE TITLE
TODO-list for the release 4.12

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3054]
- [x] Email the announcement
- [x] Publish the Windows demos of 4.12
- [x] Update the image of https://upcoming.cgal.org/releases.html
- [x] Compile CGAL-4.12 on my machine
- [x] verify `CGAL_RELEASE_DATE` in `CGAL/version.h`
- [x] RPM packages
- [x] Manage the Github milestones
