### ISSUE TITLE
Improve CGAL testing of MacOS

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3901]
Now that @danston is on board, we hope the support of MacOS will improve. And in particular the testing.

## TODO list

- [ ] Install a new [nightly testsuite] on an updated mac (with [MacOS 10.14 (Mojave)]) using `autotest_cgal`.
  - Optionally: test with leda-numbers instead of GMP
- [ ] Upgrade or reinstall magritte with [MacOS 10.13 (High Sierra)], and resetup its testsuite.
- [ ] Improve the Brew package with a [Tap]:
  - add sources for examples and demos,
  - add precompiled examples and demos.

[MacOS 10.14 (Mojave)]: https://en.wikipedia.org/wiki/MacOS_Mojave
[MacOS 10.13 (High Sierra)]: https://en.wikipedia.org/wiki/MacOS_High_Sierra
[nightly testsuite]: https://github.com/CGAL/cgal/wiki/Testing#how-to-setup-an-automatic-nighlty-testsuite
[Tap]: https://docs.brew.sh/Taps

**Comment by danston** [comment]
Hi @lrineau. I had reworked all the points above.

* Install a new test suite on a new mac and old mac. 

I have created a test suite for clang 1001 on Mojave with two different configurations:

1. Clang default with gmp/mpfr standard number types including all dependencies except for the tensorflow, since there is no any cmake-based version that is compilable on mac os.
2. Clang leda with leda number types and all dependencies without tensorflow as above.

The same has been done on the old mac for clang 1000 on High Sierra. Moreover, I have cleaned up the whole mac by reinstalling all dependencies via brew. It is now working almost as a new one.

The clang default will be launched from Monday to Friday, while the leda one on Saturdays.

* Improve the brew package.

1. I took care of the old formula which is on homebrew-core (it had a few tiny problems). I will do a pull-request when the new release of CGAL comes out.
2. I created a tap (for the moment under my name on github for testing purposes: danston/cgal) that includes cgal@4.13, cgal@4.14, cgal-demos@4.13, cgal-demos@4.14, cgal-examples@4.13, and cgal-examples@4.14 keg only CGAL distributions based on the corresponding releases (they do not interfere with any other CGAL installation). They can all be compiled including all dependencies via brew and there are also two bottles available with the precompiled results: mojave and high sierra. The installing time for all demos via the bottle is now reduced to less than 1 minute. I asked a few friends to use it and the precompiled demo works just fine. I expect more results from friends next weeks.

Since CGAL demos and examples required a few dependencies, which are not in brew core, I created a few formulas to install them via brew but pointing to the original websites: esbtl, lastools, lib3mf, librs, and bliss.

**Comment by lrineau** [comment]
Sounds great. Can you link here the pull-requests or the new tap formula?

**Comment by danston** [comment]
The tap is: [danston/cgal](https://github.com/danston/homebrew-cgal)
P.S. A few bottles for high sierra are still being compiled so they will be uploaded today/tomorrow.

**Comment by lrineau** [comment]
@danston We should refresh that tap, and see if we can contribute to `homebrew-core` directly.

**Comment by danston** [comment]
@lrineau Yes, this is a good thing to do. In fact, I keep updating the tap. It has everything there except for 5.1 since I did not have the time for that recently. And contributing to the core directly, I have to see how to do that.

**Comment by lrineau** [comment]
> @lrineau Yes, this is a good thing to do. In fact, I keep updating the tap. It has everything there except for 5.1 since I did not have time to do that recently. And contributing to the core directly, I have to see how to do that.

What are the differences between your versions in the tap, and the one of homebrew-core? Could we contribute the diffs upstream?

**Comment by danston** [comment]
@lrineau My tap has the same version of the current release of CGAL + it also includes previous versioned releases `cgal@4.14`, `cgal@5.0`, `cgal@5.01`, etc., precompiled and bottled examples and demos, and formulas to install and compile examples and demos.
