### ISSUE TITLE
Lazy AABB::accelerate_distance_queries()

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4008]
## Issue Details

It is too easy to forget to call `AABB::accelerate_distance_queries()` before a distance query.

AABB_tree should:
  - either call it lazily the first time a distance query is made,
  - or display a warning message at runtime, about the developer forgetting to call it.

## TODO
- [x] add a function AABB::do_not_accelerate_distance_queries(), that stores a Boolean member variable,
- [x] call AABB::accelerate_distance_queries() automatically (lazily) if the Boolean is not set.
- [x] announce in the release note a change of behavior (breaking change) as the default will be with accelerate distance queries.
## Environment
* CGAL version: all versions

**Comment by afabri** [comment]
Starting from how many distance queries there is a gain?  I ask as the lazy but automatic version might be a bad idea if one does only a few queries.

**Comment by lrineau** [comment]
We should: 
  - add a function `AABB::do_not_accelerate_distance_queries()`, that stores a Boolean member variable,
  - and call `AABB::accelerate_distance_queries()` automatically (lazily) if the Boolean is not set.

**Comment by sloriot** [comment]
+ announced in the release note a change of behavior (breaking change) as the default will be with accelerate distance queries.
