### ISSUE TITLE
Errors in 4.14.1

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#4033]
## Issue Details

The 4.14.1 testsuite shows several problems : 

- [x]  [in Intersections_2](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Intersections_2/TestReport_cgaltester_x86-64_Darwin-18.2_Apple-clang-default_Release.gz) (fixed in #4037, merged)

- [x] [in mesh_3_Examples](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Mesh_3_Examples/TestReport_lrineau_CentOS6-32.gz) (fixed in #4038, merged)

- [x] apparently there is some c++11 in [Triangulation_2 ](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.1-I-173.shtml#Triangulation_2) (fixed in #4036, merged)

- [x] [in the Classification_plugin of the demo](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Polyhedron_Demo/TestReport_gimeno_CentOS7.gz) (fixed in #4048, merged)

- [x] there are some new uninitialized variables in [Kernel_23](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.1-I-173.shtml#Kernel_23) (fixed by #4040, merged)

- [x] <s>and some warnings in [Generator](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.1-I-173.shtml#Generator)</s>(have been there in CGAL since early 2018: that depends on the Boost version)

- [x] Also, recent testsuites have shown problemes on Gauguin : 
In debug `std::byte` is said to be ambiguous, and in Release mode the Polyhedorn demo is drowning in boost errors. (fixed by #4034, merged)

## Environment

* CGAL version:4.14.1

**Comment by lrineau** [comment]
I think our Travis tests should use the compiler flag `std=c++03` in the release branches for 4.13.x and 4.14.y.

**Comment by lrineau** [comment]
The warnings in Generator, about uninitialized stuff in `boost::random::binomial_distribution` have been [there in CGAL since early 2018][1]: that depends on the Boost version.

[1]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-168/Generator_Demo/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz

**Comment by lrineau** [comment]
As for the compilation error in Classsification plugin, I let @sgiraudot deal with it once he comes back.
```
/home/cgal_tester/build/src/cmake/platforms/CentOS7/test/Polyhedron_Demo/Plugins/Classification/Cluster_classification.cpp:942:50:   required from here
/usr/include/boost/utility/result_of.hpp:166:8: error: no class template named 'result' in 'const struct CGAL::Classification::Cluster<ItemRange, ItemMap>::bbox() const [with ItemRange = Point_set_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> >; ItemMap = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >]::__lambda1'
 struct result_of_nested_result : F::template result<FArgs>
        ^
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Polyhedron_Demo/TestReport_gimeno_CentOS7.gz

It is very recent. Probably because of https://github.com/CGAL/cgal/pull/3961.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jun 27, 2019, 1:49 PM GMT+2](https://github.com/CGAL/cgal/issues/4033#issuecomment-506313810 "2019-06-27T11:49:54Z - Replied by Github Reply Comments"):
> As for the compilation error in Classsification plugin, I let @sgiraudot deal with it once he comes back.
> ```
> /home/cgal_tester/build/src/cmake/platforms/CentOS7/test/Polyhedron_Demo/Plugins/Classification/Cluster_classification.cpp:942:50:   required from here
> /usr/include/boost/utility/result_of.hpp:166:8: error: no class template named 'result' in 'const struct CGAL::Classification::Cluster<ItemRange, ItemMap>::bbox() const [with ItemRange = Point_set_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> >; ItemMap = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >]::__lambda1'
>  struct result_of_nested_result : F::template result<FArgs>
>         ^
> ```
> https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Polyhedron_Demo/TestReport_gimeno_CentOS7.gz
> 
> It is very recent. Probably because of https://github.com/CGAL/cgal/pull/3961.

@sgiraudot I hope you will have time pretty soon to have a look at the issue and produce a pull-request.

**Comment by sgiraudot** [comment]
I introduced a lambda+auto in this PR and it was destined to 4.13 (not 5.0 with C++11/14), which is obviously wrong... I'll fix it right away.

**Comment by lrineau** [comment]
Should be fixed, now that all PR are merged.
