### ISSUE TITLE
 5.1 release check list

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4352]
# Before the beta release
- [x] Update of the Supported platforms.
- [x] Update the `public_release_name`
- [x] Update the file `Installation/include/CGAL/version.h` (for header-only)
- [x] change the crontab to add `--beta 1` to the command line
- [x] Diff of the change log of 5.1 with 5.0 to check only 5.1 was modified.
- [x] Add links to the file `CHANGES.md` (#4714)
- [x] Rewrap the file `CHANGES.md` (#4714)
- [x] Reorder the file `CHANGES.md` (#4714)
- [x] Update `Documentation/doc/resources/1.8.13/menu_version.js` and the other two copies
- [x] Prepare the announcement mail of the beta release
- [x] Prepare the modification of the web site, in upcoming (announcement plus release graph)
- [x] open the milestone for the release
- [x] remove `cpp11`, `BOOST_FOREACH` and co introduced by a merge of 4.14 branch (https://github.com/CGAL/cgal/pull/4774)
- [x] Create new tables for features/small features with closed review for the next release

# After the beta release
- [x] change the crontab to add `--beta 2` to the command line
- [x] Update the file `Installation/include/CGAL/version.h` (for header-only)
- [x] Update the file `Installation/lib/cmake/CGAL/CGALConfigVersion.cmake`
- [x] clone the milestone
- [x] PR for brew package: https://github.com/Homebrew/homebrew-core/pull/58804
- [x] PR for vcpkg: https://github.com/microsoft/vcpkg/pull/12614
- [x] RPM for Fedora: https://bodhi.fedoraproject.org/updates/?packages=CGAL
- [x] Update `/wiki/Releases`
- [x] Update https://www.cgal.org/releases.html and change the post flags (latest-beta-release)
- [x] Upload the pre-compiled demos

# Before the official release
- [x] Update the `public_release_name`
- [x] Update the file `Installation/include/CGAL/version.h` (for header-only)
- [x] change the crontab to remove `--beta 1` from the command line
- [x] Update `menu_version.js` in the documentation.
- [x] remove `cpp11`, `BOOST_FOREACH` and co introduced by a merge of 4.14 branch

# After the official release
- [x] Tag PRs with `bash tag_pr_per_release.sh` (see https://github.com/CGAL/cgal/pull/4000)
- [x] Update `/home/lrineau/CGAL/create_internal_release` on cgal.gf.com
- [x] Update the bug-fix number in the branch
- [x] Update `/wiki/Releases`
- [x] Update https://github.com/CGAL/cgal/wiki/Internal-Releases
- [x] Create a new issue for the check list of the next release: https://github.com/CGAL/cgal/issues/4989
- [x] Update https://www.cgal.org/releases.html and change the post flags (latest-release) + remove the beta flag (latest-beta-release)
- [x] Update Travis config file of cgal-swig-bindings: pending https://github.com/CGAL/cgal-swig-bindings/pull/181
- [x] Re-upload the pre-compiled demos
- [x] update PR for brew package: https://github.com/Homebrew/homebrew-core/pull/60809
- [x] update PR for vcpkg: pending https://github.com/microsoft/vcpkg/pull/12614
- [x] update RPM for Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2020-e9011e9454
- [x] Add news entry for cgal-web
- [x] RW rules for group name changes in #4209 

# After a bug-fix release 5.1.2
- [x] Tag PRs with `bash tag_pr_per_release.sh` (see https://github.com/CGAL/cgal/pull/4000)
- [x] Update the bug-fix number in the branch
- [x] Update `/wiki/Releases`
- [x] Update https://www.cgal.org/releases.html and change the post flags (latest-release) + remove the beta flag (latest-beta-release)
- [ ] Re-upload the pre-compiled demos
- [ ] update PR for brew package: 
- [ ] update PR for vcpkg: 
- [ ] update RPM for Fedora:
- [ ] Add news entry for cgal-web

# After a bug-fix release 5.1.3
- [x] Tag PRs with `bash tag_pr_per_release.sh` (see https://github.com/CGAL/cgal/pull/4000)
- [x] Update the bug-fix number in the branch
- [x] Update `/wiki/Releases`
- [x] Update https://www.cgal.org/releases.html and change the post flags (latest-release) + remove the beta flag (latest-beta-release)
- [ ] Re-upload the pre-compiled demos
- [ ] update PR for brew package: 
- [ ] update PR for vcpkg: 
- [x] update RPM for Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2021-9de542ab4c
- [ ] Add news entry for cgal-web
- [x] Merge https://github.com/CGAL/cgal-web/pull/9 for the web site

# After a bug-fix release 5.1.4
- [x] Tag PRs with `bash tag_pr_per_release.sh` (see https://github.com/CGAL/cgal/pull/4000)
- [x] Update the bug-fix number in the branch
- [x] Update `/wiki/Releases`
- [x] Update https://www.cgal.org/releases.html and change the post flags (latest-release) + remove the beta flag (latest-beta-release)
- [ ] Re-upload the pre-compiled demos
- [ ] update PR for brew package: 
- [ ] update PR for vcpkg: 
- [x] update RPM for Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2021-1f600fa159
- [x] Add news entry for cgal-web

# After a bug-fix release 5.1.5
- [x] Tag PRs with `bash tag_pr_per_release.sh` (see https://github.com/CGAL/cgal/pull/4000)
- [ ] <s>Update the bug-fix number in the branch</s> (last release in that branch)
- [x] Update `/wiki/Releases`
- [ ] Re-upload the pre-compiled demos
- [ ] update PR for brew package: 
- [ ] update PR for vcpkg: 
- [x] update RPM for Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2021-e173d9ce92
- [ ] Add news entry for cgal-web

Next release checklist: https://github.com/CGAL/cgal/issues/4989 (CGAL-5.2).

**Comment by lrineau** [comment]
I think I am done with this check-list. There are two pending pull-requests to finish the TODO list:
- https://github.com/CGAL/cgal-swig-bindings/pull/181 to test the bindings with 5.1, and
- https://github.com/microsoft/vcpkg/pull/12614 that updates the vcpkg package to CGAL-5.1.
