### ISSUE TITLE
Review PR Mesh_3 for CGAL-5.6

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7369]
```[tasklist]
### Tasks
- [x] https://github.com/CGAL/cgal/pull/7116
- [x] https://github.com/CGAL/cgal/pull/7315
- [x] https://github.com/CGAL/cgal/pull/7307
```
