### ISSUE TITLE
Triangulation_3 fix segment traverser

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7438]
```[tasklist]
### Tasks
- [x] Question to answer: should the locate types of `_cur` and `_prev` always be equal?
- [x] [Jane] In the simplex traverser, replace all cases with `OUTSIDE_AFFINE_HULL` by tests of `cell_iterator == end()`,
- [x] [Jane] In the simplex traverser, always use `ltprev` (and never `ltnext`).
- [x] [Laurent] Fix those locate types for corner cases (like "outside convex hull", or "target is on a edge/facet"
- [ ] [Laurent] add tests of the traverser with a 2D triangulation
- [ ] #7130
```

### Note
- When `_cur` is `Cell_handle()` then the locate type is meaningless (for the moment, it is `OUTSIDE_AFFINE_HULL`).
- The locate types of `_cur` and `_prev` are always equal, *but* when `_cur` is the end (`Cell_handle()`), or when `_prev` is `Cell_handle()`.

**Comment by lrineau** [comment]
We could close this issue. The remaining task, about the 2D issue, is already reported as issue #7130.
