### ISSUE TITLE
TestSuite: Dump all crucial info more clearly (CXX_flags, dependency info...).

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#8165]
```[tasklist]
### Tasks
- [ ] https://github.com/CGAL/cgal/issues/8473
- [ ] https://github.com/CGAL/cgal/issues/8250
- [ ] https://github.com/CGAL/cgal/issues/8236
```
