### ISSUE TITLE
TODO list after PR #8170  CGAL improvement backported from CDT_3 branch

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8219]
_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/8170#issuecomment-2124715682_:

```[tasklist]
### Commits that were reverted and might be useful to restore in CGAL-6.1...
- [x] the fix about the CMake warning on VTK and `VTK_USE_FILE` f39b90670b5812801c86abfe818de3a18d2c134b, because it seems we still test with a VTK version 8.2,
- [ ] and the experiment to make `Segment_3` tuple-like ac47f30cd8a0921e52e3bd2a88fb435092eef837, because it is useless, and make Apple Clang emit a dubious warning, that is not easy to work around.
- [x] use `boost::unordered_flat_map` to optimize `Polyline_constraint_hierarchy_2`: 1ca6c17a2a165dccb2204f01d38d6d3d903d11c9.
```

```[tasklist]
### Functor to document in the `Kernel` concept
- [x] add `Compare_angle_3(Point_3, Point_3, Point_3, Point_3, Point_3, Point_3)` (with six points) **TODO: needs doc**
```

**Comment by sloriot** [comment]
Only the VTK item seems eligible for 6.0 IMO.

**Comment by sloriot** [comment]
@lrineau is this handled by https://github.com/CGAL/cgal/pull/8273?
