### ISSUE TITLE
new machine ovh2024.geometryfactory.com

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8352]
That machine will eventually replace `cgal.geometryactory.com` (that is currently `ovh2014.geometryfactory.com`).

```[tasklist]
### Tasks
- [ ] https://github.com/CGAL/cgal/issues/8353
- [x] install `etckeeper`
- [x] restore sshd server keys
- [x] backup `/etc` (via `etckeeper` and a private backup of the Git repo)
- [ ] https://github.com/CGAL/cgal/issues/8357
- [ ] https://github.com/CGAL/cgal/issues/8376
- [x] restore GeometryFactory user accounts
- [ ] https://github.com/CGAL/cgal/issues/8377
- [x] cron services
- [x] httpd on `cgal.geometryfactory.com`
- [ ] https://github.com/CGAL/cgal/issues/8390
```
