### ISSUE TITLE
port the CGAL mediawiki to docker (and run in with podman)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8353]
See https://github.com/CGAL/cgal-mediawiki
```[tasklist]
### Tasks
- [x] port do docker-compose
- [x] allow to import a dump of the database
- [x] allow to import the existing images
- [ ] https://github.com/CGAL/cgal/issues/8374
- [x] check how to freeze the current wiki at the old ovh2014: `$wgReadOnly = "We are upgrading MediaWiki, please be patient. This wiki will be back in a few hours.";`
- [ ] https://github.com/CGAL/cgal/issues/8459
- [x] dump and import
- [x] freeze the current wiki
- [ ] https://github.com/CGAL/cgal/issues/8375
- [x] add redirections from the old wiki to this one
- [ ] https://github.com/CGAL/cgal/issues/8460
- [ ] https://github.com/CGAL/cgal/issues/8461
- [ ] https://github.com/CGAL/cgal/issues/8387
- [ ] https://github.com/CGAL/cgal/issues/8464
```

**Comment by lrineau** [comment]
Afterward, it would be nice to setup https://www.mediawiki.org/wiki/Extension:AuthManagerOAuth with the Github OAuth.

**Comment by laksh-krishna-sharma** [comment]
May I work on this issue with a little bit of your guidance?
