### ISSUE TITLE
ovh2024: restore users home directories

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8377]
```[tasklist]
### Tasks
- [x] backup home directories from ovh2014
- [x] mount home directories read-write
- [ ] add a script to move homes backup to subvolumes,
```
