### ISSUE TITLE
 [CGAL-6.0] update CGAL RPM package for Fedora 42

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8552]
## Tasks
- [x] Fedora package submitted and integrated: https://bodhi.fedoraproject.org/updates/FEDORA-2024-ef3e0ed533
- [ ] build and check dependent packages (see below)

## Dependant packages
- [x] `crrcsim`
- [x] `gqrx`
- [x] `meshlab`
- [x] [`octave-iso2mesh`](https://src.fedoraproject.org/rpms/octave-iso2mesh) [❌ Fedora scratch build failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=124921677) ➡️ [🐛 FTBFS bug submitted](https://bugzilla.redhat.com/show_bug.cgi?id=2319425), the author is working on a new release of iso2mesh: https://github.com/fangq/iso2mesh/pull/79#issuecomment-2420463505
- [x] [`openscad`](https://src.fedoraproject.org/rpms/openscad) [Fedora scratch build failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=124921678) ➡️ [🐛 FTBFS bug submitted](https://bugzilla.redhat.com/show_bug.cgi?id=2319591), [🩹 Debian has a patch](https://sources.debian.org/src/openscad/2021.01-7/debian/patches/Fix-build-with-newer-CGAL.patch/) ➡️ [✔️ new successful build](https://bodhi.fedoraproject.org/updates/FEDORA-2024-abb6886178)
- [x] [`prusa-slicer`](https://src.fedoraproject.org/rpms/prusa-slicer) [❌ Fedora scratch build failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=124921682) ➡️ [🐛 FTBFS bug submitted](https://bugzilla.redhat.com/show_bug.cgi?id=2319599), 👷 WIP upstream patch: https://github.com/prusa3d/PrusaSlicer/pull/13081 
- [x] `python-graph-tool`
- [x] [`SFCGAL`](https://src.fedoraproject.org/rpms/SFCGAL) [❌ Fedora scratch build failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=124921698) ➡️ [🐛 FTBFS bug submitted](https://bugzilla.redhat.com/show_bug.cgi?id=2319589), [new upstream release 2.0.0](https://gitlab.com/sfcgal/SFCGAL/-/releases/v2.0.0)
- [ ] [`valeronoi`](https://src.fedoraproject.org/rpms/valeronoi) [❌ Fedora scratch build failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=124921708) ➡️ [🐛 FTBFS bug submitted](https://bugzilla.redhat.com/show_bug.cgi?id=2319590)

**Comment by MaelRL** [comment]
@lrineau Marked as done on https://github.com/CGAL/cgal/issues/7367; this can be closed?

**Comment by lrineau** [comment]
[`valeronoi`](https://src.fedoraproject.org/rpms/valeronoi) is [FTBFS since Fedora 42](https://bugzilla.redhat.com/show_bug.cgi?id=2341499), but the others are fine, now. Closing the issue.
